spring:
  datasource:
    url: jdbc:postgresql://dev-postgres-db:5432/db_notafacil
    username: dev_user
    password: devpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: ${SPRING_JPA_SHOW_SQL:false}
    properties:
      hibernate.format_sql: ${HIBERNATE_FORMAT_SQL:false}

server:
  port: 8080

logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:INFO}
    com.notafacil: ${LOGGING_LEVEL_APP:DEBUG}
    org.hibernate.SQL: ${LOGGING_LEVEL_HIBERNATE_SQL:WARN}
    org.hibernate.type.descriptor.sql.BasicBinder: ${LOGGING_LEVEL_HIBERNATE_PARAMS:OFF}
    org.springframework.ws.client.MessageTracing: WARN
    org.springframework.ws.client.core.WebServiceTemplate: WARN

azure:
  keyvault:
    enabled: false