spring:
  profiles:
    active: dev
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5433/rpsdb
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate.format_sql: true
  webservices:
    servlet:
      load-on-startup: -1
    path: /ws
  jvm:
    system-properties:
      azure.keyvault.jca.certificates-refresh-interval-in-ms: 3600000
      azure.keyvault.jca.keys-refresh-interval-in-ms: 3600000
      azure.keyvault.jca.disable-challenge-resource-verification: true
      azure.tokenCredentialCacheEnabled: true
server:
  port: 8081



nfse:
  service:
    url: ${NFSE_SERVICE_URL:http://isshomo.sefin.fortaleza.ce.gov.br/grpfor-iss/ServiceGinfesImplService}
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
logging:
  level:
    org.springframework.ws.client.MessageTracing: TRACE
    org.springframework.ws.client.core.WebServiceTemplate: TRACE
azure:
  keyvault:
    # Endpoint do seu Key Vault
    url: ${AZURE_KEYVAULT_URL:${azure.keyvault.url:}}
    # Alias do certificado importado
    cert:
      alias: ${AZURE_KEYVAULT_CERT_ALIAS:}

  client:
    # Client ID (App Registration)
    id: ${AZURE_CLIENT_ID:}
    # Client Secret (App Registration)
    secret: ${AZURE_CLIENT_SECRET:}

  tenant:
    # Tenant ID do Azure AD
    id: ${AZURE_TENANT_ID:}



springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
    version: openapi_3_0
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    layout: BaseLayout
    custom-css: /swagger-custom.css
    defaultModelsExpandDepth: -1
    operationsSorter: method
  servers:
    - url: https://notafacil-api.adapterbot.cloud
      description: Produção
